"use client";

import { FormEvent, useState } from "react";

export function ContactForm() {
  const [sent, setSent] = useState(false);
  const handleSubmit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSent(true); event.currentTarget.reset(); };

  if (sent) return <div className="grid min-h-[460px] place-items-center rounded-3xl border border-sky-100 bg-white p-8 text-center shadow-[0_18px_55px_rgba(16,50,78,.08)]"><div><span className="mx-auto grid size-16 place-items-center rounded-full bg-sky-100 text-2xl text-brand">✓</span><h2 className="mt-6 text-2xl font-extrabold text-ink">Đã nhận thông tin của bạn</h2><p className="mx-auto mt-3 max-w-sm text-sm leading-7 text-slate-500">Đội ngũ Việt Phát sẽ liên hệ lại trong thời gian sớm nhất.</p><button type="button" onClick={() => setSent(false)} className="mt-6 rounded-full bg-brand px-6 py-3 text-sm font-bold text-white">Gửi yêu cầu khác</button></div></div>;

  return <form onSubmit={handleSubmit} className="rounded-3xl border border-slate-100 bg-white p-6 shadow-[0_18px_55px_rgba(16,50,78,.08)] sm:p-9"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-brand">Gửi yêu cầu</p><h2 className="mt-3 text-2xl font-extrabold text-ink sm:text-3xl">Chúng tôi có thể giúp gì cho bạn?</h2><p className="mt-3 text-sm leading-6 text-slate-500">Điền thông tin bên dưới, chuyên viên của Việt Phát sẽ chủ động liên hệ.</p></div><div className="mt-7 grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700">Họ và tên <span className="text-red-500">*</span><input required name="name" placeholder="Nguyễn Văn A" className="mt-2 h-12 w-full rounded-xl border border-slate-200 px-4 text-sm font-normal outline-none transition placeholder:text-slate-400 focus:border-brand focus:ring-4 focus:ring-sky-100"/></label><label className="text-sm font-semibold text-slate-700">Số điện thoại <span className="text-red-500">*</span><input required name="phone" type="tel" placeholder="0901 234 567" className="mt-2 h-12 w-full rounded-xl border border-slate-200 px-4 text-sm font-normal outline-none transition placeholder:text-slate-400 focus:border-brand focus:ring-4 focus:ring-sky-100"/></label><label className="text-sm font-semibold text-slate-700">Email<input name="email" type="email" placeholder="email@congty.vn" className="mt-2 h-12 w-full rounded-xl border border-slate-200 px-4 text-sm font-normal outline-none transition placeholder:text-slate-400 focus:border-brand focus:ring-4 focus:ring-sky-100"/></label><label className="text-sm font-semibold text-slate-700">Sản phẩm quan tâm<select name="product" defaultValue="" className="mt-2 h-12 w-full rounded-xl border border-slate-200 bg-white px-4 text-sm font-normal text-slate-600 outline-none focus:border-brand focus:ring-4 focus:ring-sky-100"><option value="" disabled>Chọn danh mục</option><option>Túi nhựa</option><option>Ống nhựa</option><option>Tấm nhựa</option><option>Thùng nhựa</option><option>Bao bì</option><option>Màng nhựa</option></select></label><label className="text-sm font-semibold text-slate-700 sm:col-span-2">Nội dung cần tư vấn <span className="text-red-500">*</span><textarea required name="message" rows={5} placeholder="Mô tả nhu cầu của bạn..." className="mt-2 w-full resize-none rounded-xl border border-slate-200 p-4 text-sm font-normal outline-none transition placeholder:text-slate-400 focus:border-brand focus:ring-4 focus:ring-sky-100"/></label></div><button type="submit" className="mt-6 w-full rounded-full bg-brand px-7 py-3.5 text-sm font-bold text-white shadow-[0_10px_25px_rgba(8,117,189,.22)] transition hover:bg-brand-dark sm:w-auto">Gửi yêu cầu tư vấn <span aria-hidden>→</span></button></form>;
}
