import Image from "next/image";
import { Footer } from "./Footer";
import { HeroSlider } from "./HeroSlider";
import { Navbar } from "./Navbar";
import { ProductCard } from "./ProductCard";
import { Stats } from "./Stats";
import { products } from "../data/products";

export function HomePage() {
  return <><Navbar/><main><HeroSlider/><Stats/>
    <section id="san-pham" className="mx-auto max-w-[1240px] px-5 py-20 sm:py-24 lg:px-8 lg:py-28"><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-bold uppercase tracking-[.24em] text-brand">Danh mục nổi bật</p><h2 className="mt-4 text-3xl font-extrabold tracking-[-.025em] text-ink sm:text-4xl">Sản phẩm của chúng tôi</h2><p className="mt-4 text-sm leading-7 text-slate-500 sm:text-base">Đa dạng sản phẩm, đáp ứng linh hoạt yêu cầu của từng ngành nghề và quy mô vận hành.</p></div><div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{products.map((product) => <ProductCard key={product.id} product={product}/>)}</div></section>
    <section id="gioi-thieu" className="bg-surface py-20 sm:py-24"><div className="mx-auto grid max-w-[1240px] items-center gap-10 px-5 lg:grid-cols-2 lg:gap-16 lg:px-8"><div className="relative aspect-[4/3] overflow-hidden rounded-3xl"><Image fill sizes="(max-width: 1024px) 100vw, 50vw" src="https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1200&q=90" alt="Kỹ sư tại nhà máy sản xuất" className="object-cover"/><div className="absolute bottom-5 left-5 rounded-2xl bg-white/95 px-5 py-4 shadow-xl backdrop-blur"><strong className="block text-2xl font-extrabold text-brand">ISO 9001:2015</strong><span className="text-xs text-slate-500">Hệ thống quản lý chất lượng</span></div></div><div><p className="text-xs font-bold uppercase tracking-[.24em] text-brand">Về Cửu Long STA</p><h2 className="mt-4 text-3xl font-extrabold leading-tight tracking-[-.025em] sm:text-4xl">Nền tảng vững chắc cho mọi hoạt động sản xuất</h2><p className="mt-5 text-sm leading-7 text-slate-600 sm:text-base">Từ tư vấn lựa chọn vật liệu đến sản xuất và giao hàng, đội ngũ Cửu Long STA kiểm soát chặt chẽ từng công đoạn để mang đến chất lượng đồng nhất.</p><div className="mt-7 grid gap-4 sm:grid-cols-2">{["Nguyên liệu đạt chuẩn", "Quy trình hiện đại", "Giao hàng toàn quốc", "Hỗ trợ tận tâm"].map((item) => <div key={item} className="flex items-center gap-3 text-sm font-semibold"><span className="grid size-6 place-items-center rounded-full bg-sky-100 text-xs text-brand">✓</span>{item}</div>)}</div></div></div></section>
    <section id="tin-tuc" className="mx-auto max-w-[1240px] px-5 py-20 text-center sm:py-24 lg:px-8"><p className="text-xs font-bold uppercase tracking-[.24em] text-brand">Cam kết của chúng tôi</p><h2 className="mx-auto mt-4 max-w-2xl text-3xl font-extrabold tracking-[-.025em] sm:text-4xl">Chất lượng tạo niềm tin, bền vững tạo tương lai</h2><div className="mt-12 grid gap-6 md:grid-cols-3">{[["01", "Chất lượng ổn định", "Sản phẩm được kiểm định kỹ lưỡng trước khi xuất xưởng."], ["02", "Giải pháp phù hợp", "Tư vấn theo đúng nhu cầu sử dụng và ngân sách thực tế."], ["03", "Đồng hành lâu dài", "Dịch vụ hậu mãi nhanh chóng trong suốt vòng đời sản phẩm."]].map(([n,t,d]) => <article key={n} className="rounded-2xl border border-slate-200 p-7 text-left"><span className="text-3xl font-extrabold text-sky-100">{n}</span><h3 className="mt-6 text-lg font-bold">{t}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{d}</p></article>)}</div></section>
    <section className="bg-brand"><div className="mx-auto flex max-w-[1240px] flex-col items-start justify-between gap-7 px-5 py-12 text-white sm:flex-row sm:items-center lg:px-8"><div><h2 className="text-2xl font-extrabold sm:text-3xl">Bạn đang cần giải pháp phù hợp?</h2><p className="mt-2 text-sm text-white/70">Đội ngũ chuyên gia của chúng tôi sẵn sàng hỗ trợ.</p></div><a href="tel:0901234567" className="rounded-full bg-white px-7 py-3.5 text-sm font-bold text-brand shadow-lg">Gọi 0901 234 567</a></div></section>
  </main><Footer/></>;
}

