import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Footer } from "@/app/components/Footer";
import { Navbar } from "@/app/components/Navbar";
import { BreadcrumbBar } from "@/app/components/Breadcrumb";

export const metadata: Metadata = { title: "Giới thiệu | Nhựa Cửu Long STA", description: "Tìm hiểu hành trình, tầm nhìn và năng lực của Nhựa Cửu Long STA." };

const values = [
  ["01", "Chất lượng", "Chất lượng là nền tảng trong mọi quyết định, từ nguyên liệu đến dịch vụ sau bán hàng."],
  ["02", "Đổi mới", "Liên tục cải tiến công nghệ và quy trình để tạo ra giải pháp hiệu quả hơn."],
  ["03", "Tận tâm", "Lắng nghe nhu cầu, tư vấn minh bạch và đồng hành lâu dài cùng khách hàng."],
  ["04", "Bền vững", "Cân bằng hiệu quả kinh doanh với trách nhiệm dành cho cộng đồng và môi trường."],
];
const milestones = [["2011", "Khởi đầu hành trình", "Thành lập xưởng sản xuất đầu tiên tại TP. Hồ Chí Minh."], ["2016", "Mở rộng quy mô", "Đầu tư dây chuyền hiện đại và phát triển mạng lưới phân phối."], ["2020", "Chuẩn hóa chất lượng", "Áp dụng hệ thống quản lý chất lượng theo tiêu chuẩn ISO 9001:2015."], ["2026", "Vươn tầm toàn quốc", "Phục vụ hơn 2.000 khách hàng tại 63 tỉnh thành."]];

export default function AboutPage() {
  return <><Navbar/><BreadcrumbBar items={[{ label: "Trang chủ", href: "/" }, { label: "Giới thiệu" }]}/><main>
    <section className="bg-[#f5f9fc]"><div className="mx-auto grid max-w-[1240px] items-center gap-12 px-5 pb-12 pt-8 sm:pb-20 sm:pt-12 lg:grid-cols-[1.05fr_.95fr] lg:gap-20 lg:px-8"><div className="relative"><div className="relative aspect-[4/3] overflow-hidden rounded-3xl"><Image fill sizes="(max-width:1024px) 100vw, 55vw" src="https://images.unsplash.com/photo-1581091226033-d5c48150dbaa?auto=format&fit=crop&w=1400&q=90" alt="Đội ngũ kỹ sư Cửu Long STA" className="object-cover"/></div><div className="absolute -bottom-6 right-5 rounded-2xl bg-brand px-6 py-5 text-white shadow-2xl sm:right-[-24px]"><strong className="block text-3xl font-extrabold">15+</strong><span className="text-xs text-white/75">Năm phát triển bền vững</span></div></div><div><p className="text-xs font-bold uppercase tracking-[.24em] text-brand">Câu chuyện Cửu Long STA</p><h2 className="mt-4 text-3xl font-extrabold leading-tight tracking-[-.025em] sm:text-4xl">Từ một xưởng nhỏ đến đối tác tin cậy của hàng nghìn doanh nghiệp</h2><div className="mt-6 space-y-4 text-sm leading-7 text-slate-600 sm:text-base"><p>Cửu Long STA được hình thành từ một mong muốn giản dị: tạo ra những sản phẩm nhựa chất lượng, phù hợp với điều kiện vận hành thực tế của doanh nghiệp Việt.</p><p>Qua từng giai đoạn, chúng tôi kiên định đầu tư vào công nghệ, con người và hệ thống quản lý. Mỗi sản phẩm xuất xưởng không chỉ đáp ứng yêu cầu kỹ thuật mà còn mang theo cam kết về sự bền bỉ và trách nhiệm.</p></div><div className="mt-8 flex gap-8 border-t border-slate-200 pt-7"><div><strong className="block text-2xl font-extrabold text-brand">2.000+</strong><span className="text-xs text-slate-500">Khách hàng</span></div><div><strong className="block text-2xl font-extrabold text-brand">120+</strong><span className="text-xs text-slate-500">Dòng sản phẩm</span></div><div><strong className="block text-2xl font-extrabold text-brand">63</strong><span className="text-xs text-slate-500">Tỉnh thành</span></div></div></div></div></section>
    <section className="bg-surface py-20 sm:py-24"><div className="mx-auto grid max-w-[1240px] gap-6 px-5 md:grid-cols-2 lg:px-8"><article className="rounded-3xl bg-[#082b45] p-8 text-white sm:p-11"><span className="text-xs font-bold uppercase tracking-[.22em] text-sky-300">Tầm nhìn</span><h2 className="mt-5 text-2xl font-extrabold sm:text-3xl">Trở thành doanh nghiệp nhựa công nghiệp được tin chọn hàng đầu Việt Nam</h2><p className="mt-5 text-sm leading-7 text-white/65">Dẫn đầu bằng chất lượng, công nghệ và những giải pháp có trách nhiệm với tương lai.</p></article><article className="rounded-3xl bg-brand p-8 text-white sm:p-11"><span className="text-xs font-bold uppercase tracking-[.22em] text-white/65">Sứ mệnh</span><h2 className="mt-5 text-2xl font-extrabold sm:text-3xl">Tạo ra giải pháp thiết thực, nâng cao hiệu quả cho khách hàng</h2><p className="mt-5 text-sm leading-7 text-white/75">Mang đến sản phẩm ổn định, dịch vụ tận tâm và giá trị lâu dài cho từng đối tác.</p></article></div></section>
    <section className="py-20 sm:py-28"><div className="mx-auto max-w-[1240px] px-5 lg:px-8"><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-bold uppercase tracking-[.24em] text-brand">Giá trị cốt lõi</p><h2 className="mt-4 text-3xl font-extrabold tracking-[-.025em] sm:text-4xl">Nguyên tắc dẫn đường cho mọi hành động</h2></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{values.map(([n,title,text]) => <article key={n} className="rounded-2xl border border-slate-200 bg-white p-7 transition hover:-translate-y-1 hover:shadow-xl"><span className="text-3xl font-extrabold text-sky-100">{n}</span><h3 className="mt-7 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{text}</p></article>)}</div></div></section>
    <section className="bg-[#071d2e] py-20 text-white sm:py-24"><div className="mx-auto max-w-[1040px] px-5 lg:px-8"><div className="text-center"><p className="text-xs font-bold uppercase tracking-[.24em] text-sky-300">Hành trình phát triển</p><h2 className="mt-4 text-3xl font-extrabold sm:text-4xl">Những cột mốc đáng nhớ</h2></div><div className="relative mt-14 grid gap-7 md:grid-cols-4"><div className="absolute left-0 right-0 top-[9px] hidden h-px bg-white/15 md:block"/>{milestones.map(([year,title,text]) => <article key={year} className="relative border-l border-white/15 pl-6 md:border-l-0 md:pl-0 md:pt-10"><span className="absolute -left-[5px] top-1 size-2.5 rounded-full bg-sky-400 ring-4 ring-[#0d3048] md:left-0 md:top-1"/><strong className="text-2xl font-extrabold text-sky-300">{year}</strong><h3 className="mt-3 font-bold">{title}</h3><p className="mt-2 text-xs leading-6 text-white/50">{text}</p></article>)}</div></div></section>
    <section className="relative overflow-hidden bg-brand"><div className="mx-auto flex max-w-[1240px] flex-col items-start justify-between gap-7 px-5 py-14 text-white sm:flex-row sm:items-center lg:px-8"><div><h2 className="text-2xl font-extrabold sm:text-3xl">Cùng Cửu Long STA tạo nên giá trị bền vững</h2><p className="mt-2 text-sm text-white/70">Chúng tôi sẵn sàng lắng nghe và đồng hành cùng dự án của bạn.</p></div><Link href="/lien-he" className="rounded-full bg-white px-7 py-3.5 text-sm font-bold text-brand shadow-lg">Liên hệ với chúng tôi</Link></div></section>
  </main><Footer/></>;
}
